name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Skip Node build when pnpm-lock.yaml is absent
        if: ${{ hashFiles('**/pnpm-lock.yaml') == '' }}
        run: echo "No pnpm-lock.yaml found. Skipping Node build steps."

      - name: Setup pnpm
        if: ${{ hashFiles('**/pnpm-lock.yaml') != '' }}
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node.js
        if: ${{ hashFiles('**/pnpm-lock.yaml') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: |
            **/pnpm-lock.yaml

      - name: Install dependencies
        if: ${{ hashFiles('**/pnpm-lock.yaml') != '' }}
        run: pnpm install --frozen-lockfile

      - name: Build
        if: ${{ hashFiles('**/pnpm-lock.yaml') != '' }}
        run: pnpm run build

      - name: Typecheck
        if: ${{ hashFiles('**/pnpm-lock.yaml') != '' }}
        run: pnpm run typecheck
        continue-on-error: true

      - name: Lint
        if: ${{ hashFiles('**/pnpm-lock.yaml') != '' }}
        run: pnpm run lint
        continue-on-error: true

      - name: Test
        if: ${{ hashFiles('**/pnpm-lock.yaml') != '' }}
        run: pnpm run test --if-present
        continue-on-error: true